name: Mi Pipeline de DevOps  

on: [push]  

jobs:
  build-and-test:  
    runs-on: ubuntu-latest  

    steps:
      - name: Descargar el código
        uses: actions/checkout@v3  

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  

      - name: Ejecutar Pruebas (CI)
        run: |
          python tes_app.py